exports.blocks = [
    { name: 'i-global' },
    { name: 'scaffolding' },
    { name: 'grid' },
    { name: 'layout' },
    { name: 'type' },
    { name: 'code' },
    { name: 'form' },
    { name: 'table' },
    { name: 'sprites' },
    { name: 'dropdowns' },
    { name: 'wells' },
    { name: 'component-animations' },
    { name: 'close' },
    { name: 'btn', mods: [
        { name: 'type', vals: ['danger', 'info', 'inverse', 'link', 'primary', 'success', 'warning'] },
        { name: 'size', vals: ['large', 'small', 'mini'] },
        { name: 'block', vals: ['yes'] }
    ]},
    { name: 'button-groups' },
    { name: 'alerts' },
    { name: 'navs' },
    { name: 'navbar' },
    { name: 'breadcrumbs' },
    { name: 'pagination' },
    { name: 'pager' },
    { name: 'modals' },
    { name: 'tooltip' },
    { name: 'popovers' },
    { name: 'thumbnails' },
    { name: 'labels-badges' },
    { name: 'progress', mods: [
        { name: 'active', vals: ['yes'] },
        { name: 'danger', vals: ['yes'] },
        { name: 'info', vals: ['yes'] },
        { name: 'striped', vals: ['yes'] },
        { name: 'success', vals: ['yes'] },
        { name: 'warning', vals: ['yes'] },
    ]},
    { name: 'accordion' },
    { name: 'carousel' },
    { name: 'hero-unit' }
]
